apiVersion: v1
kind: Service
metadata:
  name: {{ template "colinlabs.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ template "colinlabs.name" .  }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app: {{ .Release.Name }}
    release: {{ template "colinlabs.name" .  }}
